#' Trends in Yearly Energy Generation Graphing Function
#' 
#' This function will take a summary table generated by yr_engen() and graph the trends over time of the selected parameter for a single plant
#' @param df The dataframe with the summary data to graph
#' @param year The column with year values to graph on the X axis
#' @param para The column with the parameter values to graph on the y axis
#' @keywords energy
#' @return Function will return a graph for a single energy plant of the mean of a parameter over time
#' @examples
#' yr_engen_gr(mon_gen_mo_al, "Year", "Percent.Generation")


yr_engen_gr <- function(df, year, para) {
  df_gr <- ggplot(df, aes(df[ , year], df[ , para])) +
    geom_point() +
    xlab(year) +
    ylab(para) +
    ylim(0,1) 
  return(df_gr)
}